function Graficarpr5(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y
 
%  Auto-generated by MATLAB on 28-Feb-2020 17:31:00
 
% Create figure
figure1 = figure('NumberTitle','off','Name','Figure');
 
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
 
% Create stem
stem(X1,Y1,'MarkerFaceColor',[0 0.749019622802734 0.749019622802734],...
'MarkerEdgeColor',[0 0.749019622802734 0.749019622802734],...
'LineWidth',2,...
'Color',[0 0.749019622802734 0.749019622802734]);
 
% Create ylabel
ylabel('x[n]');
 
% Create xlabel
xlabel('n');
 
% Create title
title('Gráfica original: x[n]');
 
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-8 19]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-1 4]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.831372559070587 0.815686285495758 0.7843137383461],...
'XAxisLocation','origin','XColor',...
[0.0784313753247261 0.168627455830574 0.549019634723663],'XGrid','on',...
'XTick',[-8 -6 -4 -2 0 2 4 6 8 10 12 14 16 18 19],'YAxisLocation','origin',...
'YColor',[0.0784313753247261 0.168627455830574 0.549019634723663],'YGrid',...
'on','YTick',[-1 0 1 2 3 4],'ZColor',...
[0.0784313753247261 0.168627455830574 0.549019634723663]);
