function Graficarpr1(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y
 
%  Auto-generated by MATLAB on 28-Feb-2020 07:51:09
 
% Create figure
figure1 = figure('NumberTitle','off','Name','Figure');
 
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
 
% Create stem
stem(X1,Y1,...
'MarkerFaceColor',[0.0705882385373116 0.211764708161354 0.141176477074623],...
'MarkerEdgeColor',[0.0705882385373116 0.211764708161354 0.141176477074623],...
'LineWidth',2,...
'Color',[0.235294118523598 0.235294118523598 0.235294118523598]);
 
% Create ylabel
ylabel('x[n]');
 
% Create xlabel
xlabel('n');
 
% Create title
title('Gráfica original: x[n]');
 
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-10 10]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-7 7]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.937254905700684 0.866666674613953 0.866666674613953],...
'XAxisLocation','origin','XColor',...
[0.34901961684227 0.200000002980232 0.329411774873734],'XGrid','on','XTick',...
[-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10],'YAxisLocation',...
'origin','YColor',[0.34901961684227 0.200000002980232 0.329411774873734],...
'YGrid','on','YTick',[-7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7],'ZColor',...
[0.34901961684227 0.200000002980232 0.329411774873734]);
