function Graficarpr6(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y
 
%  Auto-generated by MATLAB on 28-Feb-2020 20:06:23
 
% Create figure
figure1 = figure('NumberTitle','off','Name','Figure');
 
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
 
% Create stem
stem(X1,Y1,'MarkerFaceColor',[0.600000023841858 0.200000002980232 0],...
'MarkerEdgeColor',[0.600000023841858 0.200000002980232 0],...
'LineWidth',2,...
'Color',[0.600000023841858 0.200000002980232 0]);
 
% Create ylabel
ylabel('x[n]');
 
% Create xlabel
xlabel('n');
 
% Create title
title('a) Original');
 
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-6 6]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-6 6]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[1 0.843137264251709 0],'XAxisLocation','origin','XColor',...
[0.235294118523598 0.235294118523598 0.235294118523598],'XGrid','on',...
'XTick',[-8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8],'YAxisLocation',...
'origin','YColor',[0.235294118523598 0.235294118523598 0.235294118523598],...
'YGrid','on','YTick',[-2 -1 0 1 2 3 4 5 6 7 8 9 10],'ZColor',...
[0.235294118523598 0.235294118523598 0.235294118523598]);
